name: web-speed-hackathon-2023 CD

on:
  push:
    branches: [ "main" ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.2.2
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - uses: pnpm/action-setup@v2.2.2
      with:
        cache: 'pnpm'
    - run: pnpm --frozen-lockfile
    - run: pnpm build
    - run: flyctl deploy --remote-only
